language: node_js
node_js:
- 6
script:
- npm run all
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  on:
    repo: wikiwi/reassemble
    tags: true
    node: 6
  skip_cleanup: true
  email: vinh@wikiwi.io
  api_key:
    secure: EnRiK/2Ja/A2WPx2snumq26Smt9PO7zoxL50NNh5+h3YYBRR11UGTH0Z9c8o40CgaBxS3UDdn8DJZhVInHVXo+IavXSLI4aZtefwzUuHPQDlk3xgL412MZtx0d174HDVkqYouGLXa3VT+Q2S7xrr4QDfCSUFNsH1XmcJKwMRwNQR0iBItLYkuWpxL5FBuPcrsYT5J7JnNdmRSUUAUx1TNxHsWjgM7cQzSRDt633uGDLbl/rcUDs9z/QXprlhLaGpSeGeoRLhNntCEWopopDPn2QizU6eNmzox2KkJfEureoqCfQMGRkP+vr81oYTne8XyrgtlZu2lKMIab4LvOJ2xiZttrdzp8D0JAYJ/FBvzXdTsPl/Fm79ctxeEbDFgLM5XksjgeAHtLcruLRFNKH8GXEYcdVOzJQhHfjbwFUzV6aZOjLa2FDvVr3cXjFesFL0jzUld+S9NQzoul9I+CJFUkE1vC7bpCZJ5xXgEgsM2a+Ul95gBH1YriRVD+e0BkWNMuuVnMM8g41kY5G4b1nbKNwMVyKD1acJdykqJBwibzBJD9fuHJKnlh0NyU3WDFjiOzg4DAspSO3T20xX3azNSYtRelehA9nVDvXYBWQ4PU8oVSwX6/DXtVuO3u83o1TwVQ20tj5KxI7184nnyYXqjYiTLMqR0GEJh5Fjb758lvU=
